spring:
    #Jedis配置（单机版）
    jedis :
      pool :
        host : 127.0.0.1
        port : 6379
        password : password
        timeout : 0
        config :
          maxTotal : 100
          maxIdle : 10
          maxWaitMillis : 100000